export const USER_CONNECT = 'USER_CONNECT';
export const USER_DISCONNECT = 'USER_DISCONNECT';
export const STOCK_VALUE_RECEIVED = 'STOCK_VALUE_RECEIVED';
export const PERIOD_CHANGED = 'PERIOD_CHANGED';
export const HISTORY_RESULTS_RECEIVED = 'HISTORY_RESULTS_RECEIVED';
